version: "3.8"
services:
  web:
    image: nginx:1.21-alpine
    ports:
      - 8000:80
    volumes:
      - ./src:/workspace
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir:
      /workspace
    depends_on:
      - app

  app:
    build: ./docker/php
    volumes:
      - ./src:/workspace
    depends_on:
      - db

  db:
    build: ./docker/mariadb
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 33060:3306

volumes:
  db-store: